name: BrowserStack Tests

on:
  pull_request:
      branches: [ main ]
  push:
      branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: E2E Tests 🤖🤖

    steps:
    - name: Checkout 🚀🚀
      uses: actions/checkout@v4

    - name: Install dependencies ➕➕ 
      run: pip install -r requirements.txt

    - name: BrowserStack Env Setup 🔧🔧
      uses: browserstack/github-actions/setup-env@master
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: Run tests 🧪🧪
      run: browserstack-sdk robot -d ./reports -e ignore-bs tests/

    - name: Upload Reports 📖📖
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: reports
        path: reports
        retention-days: 30
        if-no-files-found: warn

    - name: Slack Notification - Success        
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: pipeline-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png
        SLACK_TITLE: 'All tests passed successfully'          
        SLACK_MESSAGE: ':robot:  Tests passed  :robot:'
        SLACK_USERNAME: SUCCESS

    - name: Slack Notification - Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: pipeline-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://cdn-icons-png.flaticon.com/512/3271/3271351.png
        SLACK_TITLE: 'Some tests failed'
        SLACK_MESSAGE: ':fire:  Tests failed  :fire:'
        SLACK_USERNAME: FAILURE

  reports:
    if: always()
    needs: [tests]
    runs-on: ubuntu-latest
    name: Reports 📚📚
    steps:
    - uses: actions/checkout@v4
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: reports
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.3
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}