name: Robot Framework Tests on BrowserStack

on:

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    name: E2E Tests 🤖🤖

    steps:
    - name: Checkout 🚀🚀
      uses: actions/checkout@v3

    - name: Setup Python 🔧🔧
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies ➕➕ 
      run: pip install -r requirements.txt

    - name: Setup BrowserStack-SDK 🔧🔧
      run: browserstack-sdk setup --framework "robot" --username ${{ secrets.BROWSERSTACK_USERNAME }} --key ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: Run tests on BrowserStack 🧪🧪
      run: browserstack-sdk robot -d ./reports tests/

    - name: Upload Reports 📖📖
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: Robot-Reports
          path: reports/
          retention-days: 30
          if-no-files-found: warn

    - name: Slack Notification - Success        
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: pipeline-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://cdn-icons-png.flaticon.com/512/1642/1642322.png
        SLACK_TITLE: 'All tests passed successfully'          
        SLACK_MESSAGE: ':robot:  Tests passed  :robot:'
        SLACK_USERNAME: SUCCESS

    - name: Slack Notification - Failure
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: pipeline-notifications
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://w7.pngwing.com/pngs/552/426/png-transparent-illustration-fail-stamp-miscellaneous-text-rectangle-thumbnail.png
        SLACK_TITLE: 'Some tests failed'
        SLACK_MESSAGE: ':fire:  Tests failed  :fire:'
        SLACK_USERNAME: FAILURE

  generate_report:
    if: always()
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download reports
      uses: actions/download-artifact@v1
      with:
        name: reports
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}